version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "123"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672" #-  Web UI | Gerenciamento visual via navegador
      - "5672:5672" #- AMQP | Comunicação entre apps e RabbitMQ
